name: Run Test Workflow
description: Submit a request to run GitHub Workflow test
title: '[Request] Run test'
labels: ['run-test']

body:
  # Markdown type fields are not included in the submitted issue body
  - type: markdown
    attributes:
      value:
        Welcome to GitHub! Please fill out the information below to run test-from-issue-crated workflow

  - type: input
    id: requester
    attributes:
      label: Requester
      description: The name of the requester.
      placeholder: Me
    validations:
      required: true

  - type: input
    id: java-version
    attributes:
      label: Java Version
      description: Java version to use.
      placeholder: '17'
    validations:
      required: true

  - type: input
    id: message
    attributes:
      label: Message
      description: Message to identity test run.
      placeholder: My message
    validations:
      required: true
