
name: publish-test-report

on:
  workflow_dispatch:
  #push:
  #  branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      checks: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean test
        #run: mvn -B package --file pom.xml

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: |
            **/target/logs/*
            **/target/reports/*
            

          #  ./target/logs/
          #  .target/reports/
          #  ./target/surefire-reports/


      - name: Upload surefire test reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: surefire-test-reports
          path: |
            **/target/surefire-reports/**/*

          #  ./target/surefire-reports/TEST*.xml


      - name: Publish Test Report
        uses: phoenix-actions/test-reporting@v8
        if: success() || failure() # always run even if the previous step fails
        with:
          name: Test Report
          path: '**/target/surefire-reports/junitreports/TEST-*.xml'
          reporter: java-junit
          list-suites: all
          list-tests: all

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    #- name: Update dependency graph
    #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
