name: test in BrowserStack

on:
  workflow_dispatch:
    inputs:
      runInBrowserstack:
        type: choice
        description: "Run in BrowserStack"
        required: true
        options: [ "true", "false" ]
        default: "false"
  #push:
  #  branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: browserstack
    permissions:
      contents: write
      checks: write

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up JDK 17
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: |
          if [ "${{ github.event.inputs.runInBrowserstack }}" == "true" ]; then
            echo ">>>>>>>>>> Running in BrowserStack <<<<<<<<<<"
            mvn clean test -DsuiteXmlFile="$GITHUB_WORKSPACE/src/test/testsuite/browserstackTest.xml" \
              -Dbrowserstack.automation=true -Dbrowserstack.config="browserstack-config/custom-config.yml" \
              -DargLine=javaagent:/home/runner/.m2/repository/com/browserstack/browserstack-java-sdk/1.27.0/browserstack-java-sdk-1.27.0.jar
          else
            echo ">>>>>>>>>> Running in GitHub Runner <<<<<<<<<<"
            mvn clean test -DsuiteXmlFile="$GITHUB_WORKSPACE/src/test/testsuite/browserstackTest.xml"
          fi
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        #run: mvn -B package --file pom.xml

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: |
            ./target/logs/
            .target/reports/
            ./target/surefire-reports/

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'
          detailed_summary: true