name: test-java-setup

on:
  workflow_dispatch:
  #push:
  #  branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      checks: write

    steps:
      - uses: actions/checkout@v3

      - name: Check system java version
        run: java -version

      - name: Print environment variables
        run: printenv

    # - name: Set up JDK 17
    #   uses: actions/setup-java@v3
    #   with:
    #     java-version: '17'
    #     distribution: 'temurin'
    #     cache: maven
    # - name: Build with Maven
    #   run: mvn test
    #run: mvn -B package --file pom.xml
