# Run test using windows server

name: window-test

on:
  workflow_dispatch:
  #push:
  #  branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest
    permissions:
      contents: write
      checks: write

    steps:
      - uses: actions/checkout@v4.1.2

      - name: Display latest commit message
        run: |
          echo "Commit message: $(git log -1 --pretty=format:"%h %s")"

      -name: Print Maven version
        run: mvn -v

      -

#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#          cache: maven
#
#      - name: Build with Maven
#        run: mvn clean test -DsuiteXmlFile="$GITHUB_WORKSPACE/src/test/testsuite/smokeTest.xml"
        #run: mvn -B package --file pom.xml

#      - name: Upload test reports
#        if: always()
#        uses: actions/upload-artifact@v3
#        with:
#          name: test-reports
#          path: |
#            **/target/logs/*
#            **/target/reports/*
          

          #  ./target/logs/
          #  .target/reports/
          #  ./target/surefire-reports/


#      - name: Upload surefire test reports
#        if: always()
#        uses: actions/upload-artifact@v3
#        with:
#          name: surefire-test-reports
#          path: |
#            **/target/surefire-reports/**/*

          #  ./target/surefire-reports/TEST*.xml


